version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/hostend
      - REDIS_URL=redis://redis:6379
      - QDRANT_URL=https://your-qdrant-cluster.com
      - STRIPE_SECRET_KEY=sk_live_...
      - STRIPE_WEBHOOK_SECRET=whsec_...
      - NGINX_PROXY_MANAGER_URL=http://nginx-proxy-manager:81
      - NGINX_PROXY_MANAGER_TOKEN=your-token
      - DOMAIN=git-contextor.corrently.cloud
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=hostend
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    restart: always

volumes:
  postgres_data: {}
